# Guidelines for defining an intervention

## Intervention type

The MAPS tool cost and effectiveness module allows users to estimate the cost, effectiveness, and cost-effectiveness of large-scale food fortification (LSFF), biofortification (via crop breeding), and agronomic biofortification interventions.

### *Food fortification*

Food fortification is the addition of vitamins and/or minerals to foods during processing to increase their nutrient content (Olson, Gavin-Smith, Ferraboschi et al., 2021). Large-scale food fortification (LSFF) is food fortification that occurs during processing at formal, centralized industries (USAID Advancing Nutrition, 2023b). In the MAPS cost and effectiveness module, LSFF food vehicle choices currently include wheat flour, maize flour, refined oil, rice, salt, and sugar. Food vehicle choices may be expanded in the future to include bouillon, margarine, and other condiments.

### *Biofortification*

Biofortification via crop breeding is the process of increasing the vitamin or mineral content of a crop by crossing parent lines with high vitamin or mineral levels over several generations to produce plants with enhanced nutrient content and desired agronomic traits (Saltzman, Birol, Bouis et al., 2013). In the MAPS cost and effectiveness module, modeling of the cost, effectiveness, and cost-effectiveness of biofortification is limited to crops for which one or more biofortified variety has been released (or is near release) (see [this table](https://www.harvestplus.org/harvestplus-biofortified-crops-map-and-table-updated-with-2020-data/) from HarvestPlus 2020 data on biofortified crops released or in testing by country). Before a biofortified seed variety is released, a 6 to 8 year process of discovery and development research is typically required (Bouis, Hotz, McClafferty et al., 2011). Because costs and effectiveness are modeled over a 10-year time horizon in MAPS (see methods below), biofortified crop varieties that are still in the discovery and developmental research phases would require a longer modeling time horizon to adequately capture costs and/or impacts after the variety is released. Therefore, when estimating the cost of biofortification via crop breeding, research costs incurred prior to in-country final testing and release of the variety are assumed sunk and are not accounted for.   

### *Agronomic biofortification*

Agronomic biofortification is the process of increasing the micronutrient content of the edible portion of a crop through applying micronutrient-enriched fertilizers to the soil (granular) and/or sprayed on the plant leaves (foliar) (de Valença, Bake, Brouwer et al., 2017). The effectiveness of agronomic biofortification has been most widely studied for zinc, selenium, and iron, though agronomic biofortification with other nutrients is also possible. In the MAPS cost and effectiveness module, default application rates and grain concentrations/expected uptake are provided for some crop and mineral combinations. These defaults can be modified by tools users, and users can use the MAPS cost and/or effectiveness modelling framework to model crop and mineral combinations without default values (users will be required to specify application rates, expected grain concentrations, etc.).  

## Intervention status

The intervention status can be set to either existing intervention program or hypothetical intervention program. This choice will impact some of the default cost and effectiveness modeling assumptions. Based on the descriptions in **Table 1** below, the user should choose the intervention status that best reflects the current status of the intervention in the specific country context.

<center>Table 1. Intervention status options</center>

```{=html}

<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0 width=864
 style='width:647.75pt;border-collapse:collapse;border:none;mso-border-alt:
 solid windowtext .5pt;mso-yfti-tbllook:1184;mso-padding-alt:0cm 5.4pt 0cm 5.4pt'>
 <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes'>
  <td width=144 valign=top style='width:108.3pt;border:solid windowtext 1.0pt;
  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><b><span lang=EN-US>Intervention type<o:p></o:p></span></b></p>
  </td>
  <td width=180 valign=top style='width:134.65pt;border:solid windowtext 1.0pt;
  border-left:none;mso-border-left-alt:solid windowtext .5pt;mso-border-alt:
  solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><b><span lang=EN-US>Intervention status<o:p></o:p></span></b></p>
  </td>
  <td width=294 valign=top style='width:220.3pt;border:solid windowtext 1.0pt;
  border-left:none;mso-border-left-alt:solid windowtext .5pt;mso-border-alt:
  solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><b><span lang=EN-US>Description<o:p></o:p></span></b></p>
  </td>
  <td width=246 valign=top style='width:184.5pt;border:solid windowtext 1.0pt;
  border-left:none;mso-border-left-alt:solid windowtext .5pt;mso-border-alt:
  solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><b><span lang=EN-US>Default modeling assumptions<o:p></o:p></span></b></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:1'>
  <td width=144 rowspan=2 style='width:108.3pt;border:solid windowtext 1.0pt;
  border-top:none;mso-border-top-alt:solid windowtext .5pt;mso-border-alt:solid windowtext .5pt;
  background:#EBEBFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>LSFF</span></p>
  </td>
  <td width=180 valign=top style='width:134.65pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#EBEBFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Existing
  intervention program</span></p>
  </td>
  <td width=294 valign=top style='width:220.3pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#EBEBFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Mandatory
  fortification standards exist for the food vehicle, including the focus
  micronutrient. </span></p>
  </td>
  <td width=246 valign=top style='width:184.5pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#EBEBFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Both
  costs and effects accrue in all 10 years of the modeling time horizon.</span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:2'>
  <td width=180 valign=top style='width:134.65pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#EBEBFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Hypothetical
  intervention program</span></p>
  </td>
  <td width=294 valign=top style='width:220.3pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#EBEBFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Either
  fortification standards for the food vehicle do not exist or the
  fortification standards do not include the focus micronutrient. </span></p>
  </td>
  <td width=246 valign=top style='width:184.5pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#EBEBFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Costs
  accrue in all 10 years of the modeling time horizon (start-up costs incurred
  in years 1-2), while effects accrue in years 3-10.</span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:3'>
  <td width=144 rowspan=2 style='width:108.3pt;border:solid windowtext 1.0pt;
  border-top:none;mso-border-top-alt:solid windowtext .5pt;mso-border-alt:solid windowtext .5pt;
  background:#E5FDFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Biofortification
  (via crop breeding)</span></p>
  </td>
  <td width=180 valign=top style='width:134.65pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#E5FDFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Existing
  intervention program</span></p>
  </td>
  <td width=294 valign=top style='width:220.3pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#E5FDFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>At
  least one biofortified variety of the crop has been released in the country. </span></p>
  </td>
  <td width=246 valign=top style='width:184.5pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#E5FDFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Both
  costs and effects accrue in all 10 years of the modeling time horizon.</span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:4'>
  <td width=180 valign=top style='width:134.65pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#E5FDFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Hypothetical
  intervention program</span></p>
  </td>
  <td width=294 valign=top style='width:220.3pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#E5FDFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>No
  biofortified variety of the crop has been released in the country, but a
  biofortified variety is expected to be released soon. </span></p>
  </td>
  <td width=246 valign=top style='width:184.5pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#E5FDFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Costs
  accrue in all 10 years of the modeling time horizon (start-up costs incurred
  in years 1-3), while effects accrue in years 4-10.</span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:5'>
  <td width=144 rowspan=2 style='width:108.3pt;border:solid windowtext 1.0pt;
  border-top:none;mso-border-top-alt:solid windowtext .5pt;mso-border-alt:solid windowtext .5pt;
  background:#FFFEE6;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Agronomic
  biofortification</span></p>
  </td>
  <td width=180 valign=top style='width:134.65pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#FFFEE6;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Existing
  intervention program</span></p>
  </td>
  <td width=294 valign=top style='width:220.3pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#FFFEE6;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Granular
  and/or foliar biofortification of the crop is being promoted and adopted at a
  scale larger than pilot programs in the country. </span></p>
  </td>
  <td width=246 valign=top style='width:184.5pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#FFFEE6;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Both
  costs and effects accrue in all 10 years of the modeling time horizon.</span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:6;mso-yfti-lastrow:yes'>
  <td width=180 valign=top style='width:134.65pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#FFFEE6;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Hypothetical
  intervention program</span></p>
  </td>
  <td width=294 valign=top style='width:220.3pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#FFFEE6;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Granular
  and/or foliar biofortification of the crop is not being promoted and adopted
  at a scale larger than pilot programs in the country. </span></p>
  </td>
  <td width=246 valign=top style='width:184.5pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#FFFEE6;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Costs
  accrue in all 10 years of the modeling time horizon (start-up costs incurred
  in years 1-2), while effects accrue in years 3-10.</span></p>
  </td>
 </tr>
</table>
```
## Nature of intervention

The user choice regarding the nature of the intervention will determine how the intervention is modeled over. The choices for the nature of the intervention depend on the type of intervention and whether the intervention is existing or hypothetical (see **Table 2**).

Selecting the nature of the intervention at this stage will impact several of the default cost and effectiveness model parameter values, but all of these values can be changed by the user within the cost and effectiveness module. As such, users need not worry about selecting the “right” nature of intervention option. For example, if the user wants to model an existing LSFF intervention with both improved compliance and a revision of the current standard, the user can choose either “Improved compliance” of “Revision of existing standard” and then carefully review and edit the default parameter values to ensure the model parameters reflect the intervention characteristics they are hoping to model. 

<center>Table 2: Nature of intervention</center>

```{=html}


<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0
 style='border-collapse:collapse;border:none;mso-border-alt:solid windowtext .5pt;
 mso-yfti-tbllook:1184;mso-padding-alt:0cm 5.4pt 0cm 5.4pt'>
 <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes'>
  <td width=132 valign=top style='width:98.75pt;border:solid windowtext 1.0pt;
  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><a name="_Hlk172647268"><b><span lang=EN-US>Intervention type<o:p></o:p></span></b></a></p>
  </td>
  <span style='mso-bookmark:_Hlk172647268'></span>
  <td width=156 valign=top style='width:117.0pt;border:solid windowtext 1.0pt;
  border-left:none;mso-border-left-alt:solid windowtext .5pt;mso-border-alt:
  solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='mso-bookmark:_Hlk172647268'><b><span
  lang=EN-US>Intervention status<o:p></o:p></span></b></span></p>
  </td>
  <span style='mso-bookmark:_Hlk172647268'></span>
  <td width=168 valign=top style='width:126.0pt;border:solid windowtext 1.0pt;
  border-left:none;mso-border-left-alt:solid windowtext .5pt;mso-border-alt:
  solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='mso-bookmark:_Hlk172647268'><b><span
  lang=EN-US>Nature of intervention<o:p></o:p></span></b></span></p>
  </td>
  <span style='mso-bookmark:_Hlk172647268'></span>
  <td width=192 valign=top style='width:144.0pt;border:solid windowtext 1.0pt;
  border-left:none;mso-border-left-alt:solid windowtext .5pt;mso-border-alt:
  solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='mso-bookmark:_Hlk172647268'><b><span
  lang=EN-US>Description<o:p></o:p></span></b></span></p>
  </td>
  <span style='mso-bookmark:_Hlk172647268'></span>
  <td width=216 valign=top style='width:161.75pt;border:solid windowtext 1.0pt;
  border-left:none;mso-border-left-alt:solid windowtext .5pt;mso-border-alt:
  solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='mso-bookmark:_Hlk172647268'><b><span
  lang=EN-US>When to use<o:p></o:p></span></b></span></p>
  </td>
  <span style='mso-bookmark:_Hlk172647268'></span>
 </tr>
 <tr style='mso-yfti-irow:1'>
  <td width=132 rowspan=4 valign=top style='width:98.75pt;border:solid windowtext 1.0pt;
  border-top:none;mso-border-top-alt:solid windowtext .5pt;mso-border-alt:solid windowtext .5pt;
  background:#EBEBFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='mso-bookmark:_Hlk172647268'><span lang=EN-US
  style='color:black;mso-color-alt:windowtext'>LSFF</span></span></p>
  </td>
  <span style='mso-bookmark:_Hlk172647268'></span>
  <td width=156 rowspan=3 valign=top style='width:117.0pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#EBEBFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='mso-bookmark:_Hlk172647268'><span lang=EN-US
  style='color:black;mso-color-alt:windowtext'>Existing intervention program</span></span></p>
  </td>
  <span style='mso-bookmark:_Hlk172647268'></span>
  <td width=168 valign=top style='width:126.0pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#EBEBFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='mso-bookmark:_Hlk172647268'><span lang=EN-US
  style='color:black;mso-color-alt:windowtext'>Status quo</span></span></p>
  </td>
  <span style='mso-bookmark:_Hlk172647268'></span>
  <td width=192 valign=top style='width:144.0pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#EBEBFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='mso-bookmark:_Hlk172647268'><span lang=EN-US
  style='color:black;mso-color-alt:windowtext'>Modeled fortification standards
  and compliance with standards held constant over the 10-year time horizon.</span></span></p>
  </td>
  <span style='mso-bookmark:_Hlk172647268'></span>
  <td width=216 valign=top style='width:161.75pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#EBEBFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='mso-bookmark:_Hlk172647268'><span lang=EN-US
  style='color:black;mso-color-alt:windowtext'>Relevant when you want to model
  the cost and/or effectiveness of an existing program operating at current
  levels of compliance.</span></span></p>
  </td>
  <span style='mso-bookmark:_Hlk172647268'></span>
 </tr>
 <tr style='mso-yfti-irow:2'>
  <span style='mso-bookmark:_Hlk172647268'></span>
  <td width=168 valign=top style='width:126.0pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#EBEBFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='mso-bookmark:_Hlk172647268'><span lang=EN-US
  style='color:black;mso-color-alt:windowtext'>Improved compliance</span></span></p>
  </td>
  <span style='mso-bookmark:_Hlk172647268'></span>
  <td width=192 valign=top style='width:144.0pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#EBEBFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='mso-bookmark:_Hlk172647268'><span lang=EN-US
  style='color:black;mso-color-alt:windowtext'>Investment made during years 1-2
  enhanced monitoring and evaluation. Modeled industry compliance levels scaled
  up over 10-year time horizon.</span></span></p>
  </td>
  <span style='mso-bookmark:_Hlk172647268'></span>
  <td width=216 valign=top style='width:161.75pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#EBEBFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='mso-bookmark:_Hlk172647268'><span lang=EN-US
  style='color:black;mso-color-alt:windowtext'>Relevant when you want to model
  the cost and/or effectiveness of an existing program if compliance with the
  standard improves to a specified level or a relatively newly established
  program is scaling up.</span></span></p>
  </td>
  <span style='mso-bookmark:_Hlk172647268'></span>
 </tr>
 <tr style='mso-yfti-irow:3'>
  <span style='mso-bookmark:_Hlk172647268'></span>
  <td width=168 valign=top style='width:126.0pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#EBEBFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='mso-bookmark:_Hlk172647268'><span lang=EN-US
  style='color:black;mso-color-alt:windowtext'>Revision of existing standard</span></span></p>
  </td>
  <span style='mso-bookmark:_Hlk172647268'></span>
  <td width=192 valign=top style='width:144.0pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#EBEBFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='mso-bookmark:_Hlk172647268'><span lang=EN-US
  style='color:black;mso-color-alt:windowtext'>Investment made during years 1-2
  to plan for and revise the national standard. Modeling in years 1-2 reflects
  the current standard, while <span class=SpellE>years</span> 3-10 reflect the
  revised standard.</span></span></p>
  </td>
  <span style='mso-bookmark:_Hlk172647268'></span>
  <td width=216 valign=top style='width:161.75pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#EBEBFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='mso-bookmark:_Hlk172647268'><span lang=EN-US
  style='color:black;mso-color-alt:windowtext'>Relevant when you want to model
  the cost and or effectiveness of modifying an existing national standard,
  such as a change to the fortification level, a change to the required
  micronutrient compound, or the addition of a new micronutrient to the
  standard.</span></span></p>
  </td>
  <span style='mso-bookmark:_Hlk172647268'></span>
 </tr>
 <tr style='mso-yfti-irow:4'>
  <span style='mso-bookmark:_Hlk172647268'></span>
  <td width=156 valign=top style='width:117.0pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#EBEBFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='mso-bookmark:_Hlk172647268'><span lang=EN-US
  style='color:black;mso-color-alt:windowtext'>Hypothetical intervention
  program</span></span></p>
  </td>
  <span style='mso-bookmark:_Hlk172647268'></span>
  <td width=168 valign=top style='width:126.0pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#EBEBFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='mso-bookmark:_Hlk172647268'><span lang=EN-US
  style='color:black;mso-color-alt:windowtext'>New food vehicle</span></span></p>
  </td>
  <span style='mso-bookmark:_Hlk172647268'></span>
  <td width=192 valign=top style='width:144.0pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#EBEBFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='mso-bookmark:_Hlk172647268'><span lang=EN-US
  style='color:black;mso-color-alt:windowtext'>Investments made during years
  1-2 to plan for, implement, and launch the fortification of a new food
  vehicle.</span></span></p>
  <span style='mso-bookmark:_Hlk172647268'></span>
  <p class=MsoNormal><span style='mso-bookmark:_Hlk172647268'><span lang=EN-US><o:p>&nbsp;</o:p></span></span></p>
  </td>
  <span style='mso-bookmark:_Hlk172647268'></span>
  <td width=216 valign=top style='width:161.75pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#EBEBFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='mso-bookmark:_Hlk172647268'><span lang=EN-US
  style='color:black;mso-color-alt:windowtext'>Relevant when you want to model
  the cost and/or effectiveness of introducing national standards for the
  fortification of a new food vehicle at assumed/potential levels of
  compliance. </span></span></p>
  </td>
  <span style='mso-bookmark:_Hlk172647268'></span>
 </tr>
 <tr style='mso-yfti-irow:5'>
  <td width=132 rowspan=3 valign=top style='width:98.75pt;border:solid windowtext 1.0pt;
  border-top:none;mso-border-top-alt:solid windowtext .5pt;mso-border-alt:solid windowtext .5pt;
  background:#E5FDFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Biofortification
  (via crop breeding)</span></p>
  </td>
  <td width=156 rowspan=2 valign=top style='width:117.0pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#E5FDFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Existing
  intervention program</span></p>
  </td>
  <td width=168 valign=top style='width:126.0pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#E5FDFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Status
  quo</span></p>
  </td>
  <td width=192 valign=top style='width:144.0pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#E5FDFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Modeled
  farmer adoption rates held constant over 10-year time horizon.</span></p>
  </td>
  <td width=216 valign=top style='width:161.75pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#E5FDFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Relevant
  when you want to model the cost and/or effectiveness of an existing program
  operating at current farmer adoption rates.</span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:6'>
  <td width=168 valign=top style='width:126.0pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#E5FDFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Scale
  up</span></p>
  </td>
  <td width=192 valign=top style='width:144.0pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#E5FDFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Investments
  made during years 1-3 to promote farmer adopt of the biofortified crop.
  Modeled farmer adoption rates scaled up over 10-year time horizon.</span></p>
  </td>
  <td width=216 valign=top style='width:161.75pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#E5FDFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Relevant
  when you want to model the cost and/or effectiveness of an existing program
  if farmer adoption rates increase.</span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:7'>
  <td width=156 valign=top style='width:117.0pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#E5FDFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Hypothetical
  intervention program</span></p>
  </td>
  <td width=168 valign=top style='width:126.0pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#E5FDFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>New
  biofortified crop</span></p>
  </td>
  <td width=192 valign=top style='width:144.0pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#E5FDFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Investments
  made during years 1-3 to plan for and launch the release and promotion of the
  biofortified crop variety.</span></p>
  </td>
  <td width=216 valign=top style='width:161.75pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#E5FDFF;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Relevant
  when a biofortified crop variety is nearly ready for release and you want to
  model the cost and/or effectiveness of the new biofortified crop variety at
  assumed/potential farmer adoption rates.<span style='mso-spacerun:yes'>
  </span></span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:8'>
  <td width=132 rowspan=3 valign=top style='width:98.75pt;border:solid windowtext 1.0pt;
  border-top:none;mso-border-top-alt:solid windowtext .5pt;mso-border-alt:solid windowtext .5pt;
  background:#FFFEE6;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Agronomic
  biofortification</span></p>
  </td>
  <td width=156 rowspan=2 valign=top style='width:117.0pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#FFFEE6;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Existing
  intervention program</span></p>
  </td>
  <td width=168 valign=top style='width:126.0pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#FFFEE6;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Status
  quo</span></p>
  </td>
  <td width=192 valign=top style='width:144.0pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#FFFEE6;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Modeled
  farmer adoption rates held constant over 10-year time horizon.</span></p>
  </td>
  <td width=216 valign=top style='width:161.75pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#FFFEE6;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Relevant
  when you want to model the cost and/or effectiveness of an existing program
  operating at current farmer adoption rates.</span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:9'>
  <td width=168 valign=top style='width:126.0pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#FFFEE6;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Scale
  up</span></p>
  </td>
  <td width=192 valign=top style='width:144.0pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#FFFEE6;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Investments
  made during years 1-2 to promote farmer adoption of agronomic
  biofortification. Modeled farmer adoption rates scaled up over 10-year time
  horizon.</span></p>
  </td>
  <td width=216 valign=top style='width:161.75pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#FFFEE6;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Relevant
  when you want to model the cost and/or effectiveness of an existing program
  if farmer adoption rates increase.</span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:10;mso-yfti-lastrow:yes'>
  <td width=156 valign=top style='width:117.0pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#FFFEE6;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Hypothetical
  intervention program</span></p>
  </td>
  <td width=168 valign=top style='width:126.0pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#FFFEE6;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>New
  biofortified crop</span></p>
  </td>
  <td width=192 valign=top style='width:144.0pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#FFFEE6;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Investments
  made during years 1-2 to plan for and promote agronomic biofortification.</span></p>
  </td>
  <td width=216 valign=top style='width:161.75pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;background:#FFFEE6;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span lang=EN-US style='color:black;mso-color-alt:windowtext'>Relevant
  when you want to model the cost and/or effectiveness of a new agronomic
  biofortification program at assumed/potential farmer adoption rates.<span
  style='mso-spacerun:yes'> </span></span></p>
  </td>
 </tr>
</table>
```
