# Summary of methods used in the cost and effectiveness module of the MAPS tool

## Modeling costs in the MAPS tool

### *Type of costing and data sources*

For each type of micronutrient intervention, we have developed an activity- and ingredients-based cost model to estimate the cost of the intervention over a 10-year time horizon. That is, for each type of intervention, we have defined a series of activities required to undertake the intervention, from start-up to scale-up through annual operating activities. Then, for each activity, we have identified the types and quantities of inputs, or ingredients, that are required to execute each activity, including equipment and supplies, personnel, etc. The models are then populated with data relevant to the specific country context. It is important to note that the cost models were designed to estimate the *additional* or *incremental* cost of the interventions and exclude costs involved in the production and distribution of the food vehicle or crop in the absence of fortification or biofortification. LSFF intervention costs, for example, do not include the cost of raw materials or ingredients used to produce the food vehicle itself (e.g., wheat, oil, salt, etc.) or the labor and management costs associated with producing the food vehicle. Similarly, biofortification costs do not include farmer labor or inputs that are typically employed in the cultivation of the non-biofortified variety of the crop.

The additional or incremental activities and ingredients required to execute each type of micronutrient intervention were identified through a combination of literature reviews and interviews with international and local experts in LSFF and biofortification. Then, for Malawi and Ethiopia, country-specific data to populate each parameter of the cost models (including intervention characteristics, quantities of inputs, unit costs or the value of each input, etc.), were based on local primary data collection (interviews with government, industry, local experts, and other stakeholders), review of existing budgets, online sources (e.g., GFDx, the UNICEF supply catalogue, etc.), and the literature. The source of each parameter is documented in each cost model. The sources do not identify specific individuals or organizations. More information about specific sources is available upon request. Where no data source could be identified, the source is listed as “assumed” or “estimate”, meaning that we were unable to identify a good source of data for that parameter and had to make an informed guess about its value. Note that for hypothetical interventions, default cost model parameters are based on both data collection relevant to the specific food vehicle or crop as well as imputed based on data collected on existing, related intervention program costs (e.g., if a country has an existing wheat flour fortification program but does not have a maize flour fortification program, some of the maize flour fortification cost modeling parameters may be borrowed from the wheat flour cost data).

### *Costing perspective*

By default, intervention costs are estimated from a societal perspective, meaning that the economic value of all resources used in providing and accessing an intervention are accounted for, regardless of who incurs them (Sanders, Neumann, Basu et al., 2016). As such, the cost estimates include costs potentially paid by industry, the government, civil society (aid and donor organizations, NGOs, etc.), farmers, consumers, etc. Note that because the stakeholder groups that ultimately pays each cost is not necessarily know (e.g., what proportion of LSFF premix costs will be passed on to consumers, what proportion of industry equipment costs might directly paid by industry vs subsidized by the government or an NGO, etc., whether the incremental cost of a biofortified seed variety will be paid for by farmers or subsidized by the government, etc.), in the cost models we intentionally avoid assigning costs to specific stakeholder groups and instead refer to “industry-related” costs, “government-related” costs, etc.

For users who wish to estimate costs from a narrower perspective (e.g., government perspective), this is possible by zeroing out costs in the cost model that are expected to be paid by other stakeholder groups.

### *Economic costs*

Intervention costs also reflect the economic (vs financial) cost of inputs, meaning that the value represents the opportunity cost of the input, or the value of the input in its next best alternative use (Turner, Sandmann, Downey et al., 2023; World Health Organization, 2003). For inputs that have a market value, such as paid labor, the economic cost may be the same as the financial cost. However, for inputs that are not paid for (e.g., volunteer labor or household time to participate in an intervention) the economic cost of the input is the input’s value in its next best alternative use. Similarly, for capital costs such as equipment, the annualized economic cost accounts not only for the expected useful life of the capital good but also the assumed discount rate (3% by default) to account for the opportunity cost of using the equipment for the intervention.

In the tool, capital costs $E$ are annualized using the following equation (World Health Organization, 2003):

<center>$E = \frac{P}{A(n,r)}$</center>

*where* $A(n,r) =  \frac{1-(1+r)^{-n}}{r}$

Here, $P$ is the purchase value of the capital item, including shipping and taxes (note that this assumes the salvage value, or the value of the capital item at the end of its useful life, is zero), $n$ is the assumed useful life of the capital item, and $r$ is the discount rate.

### *Costing base year*

In the current version of the MAPS tool, costs are reported in 2021 US dollars (USD). For costs reported in USD, the value was adjusted to 2021 USD using the Bureau of Economic Analysis implicit price deflators for gross domestic product (Bureau of Economic Analysis, 2020). For costs reported in other currencies (e.g., Malawi Kwacha or Ethiopian Birr), costs were first adjusted to the 2019 value (where necessary) using the local GDP price deflator, then converted to USD using the average 2021 exchange rate. To maintain consistency, user-defined costs (i.e., costs modified by the user from the default value) should also be entered in 2021 USD.

## Modeling effectiveness in the MAPS tool

### *Effectiveness (and related) indicators*

In the MAPS tool, the effectiveness of micronutrient interventions is based on the concept of effective coverage, or the number or percent of households with inadequate apparent intake of the focus micronutrient without any interventions (that is, based on diets alone) who achieve dietary micronutrient adequacy as the result of the intervention. In the tool, the prevalence of micronutrient inadequacy and effective coverage can be calculated based on either apparent micronutrient intake per adult female equivalent (AFE) or based on the nutrient density of the household diet. Each of these approaches are described in detail below.

In addition to effective coverage, several other indicators are automatically calculated in the MAPS tool effectiveness modeling framework, as defined in **Table 3**.

| **Indicator**                        | **Definition**                                                                                                                                                                                                                                                                                                                                                     |
|----------------|--------------------------------------------------------|
| Effective coverage                   | The proportion of household with an inadequate apparent intake of the focus micronutrient at baseline (i.e., without interventions) that achieve dietary micronutrient adequacy with the specified intervention. In other words, this is the change in the prevalence of inadequacy from the baseline scenario to the modeled micronutrient intervention scenario. |
| Micronutrient inadequacy             | Estimate of the percent of households with an inadequate apparent intake of the focus micronutrient. This percentage is estimated both for the baseline scenario (i.e., without any interventions) as well as with the modeled micronutrient intervention scenario. Note that the difference in these two percentages is equivalent to effective coverage.         |
| Risk of high intakes                 | The percent of households with apparent intake of the focus micronutrient above the tolerable upper intake level (UL).                                                                                                                                                                                                                                             |
| Reach                                | The proportion of household that reported consuming the food vehicle or crop, in any quantity, during the recall period.                                                                                                                                                                                                                                           |
| Apparent consumption among consumers | The quantity of a food vehicle or crop apparently consumed among consumers (i.e., excluding household who did not consume the food vehicle or crop) per day per adult female equivalent (AFE).                                                                                                                                                                     |

: Table 3. Effective coverage and related indicators

### *Data sources and methods for modeling effectiveness and other indicators*

Effective coverage and related indicators are modeled in the MAPS tool using food consumption data from household consumption and expenditure surveys (HCESs). HCESs, also known as household income and expenditure surveys, household budget surveys, integrated household surveys, and Living Standards Measurement Study surveys, are designed to collect data on various dimensions of household socioeconomic conditions, but most surveys also include a module to collect data on household consumption of and/or expenditures on a pre-defined list of food items (Fiedler, 2013; Coates, Colaiezzi, Fiedler et al., 2012). Variation in the design of the food consumption/expenditure modules of HCESs means that there is also variation in how well-suited the resulting data are to assess the micronutrient adequacy of diets and model the impacts of micronutrient interventions (Food and Agriculture Organization of the United Nations & The World Bank, 2018). There are also a number of limitations inherent in using these data for nutrition analyses. Both of these issues are discussed in detail below. We qualify many of our estimates with the term “apparent” (e.g., apparent food consumption, apparent micronutrient intake, etc.) to emphasize the assumptions and limitations associated with using household-level food consumption data.

The methods used in the MAPS tool to assess the adequacy of the household diet without and with micronutrient interventions generally follow the steps laid out in the USAID Methods Guide for using HCES data conduct a needs assessment and design/redesign an LSFF program (USAID Advancing Nutrition, 2023a). As noted above, the MAPS tool allows for calculating effectiveness (and related) indicators based on two approached: (1) apparent intake per AFE, and (2) the nutrient density of the household diet. Based on each approach, the steps listed below describe the methods used assess the baseline apparent adequacy of the household diet for meeting the requirements of household members, to model the impact of a micronutrient intervention on the micronutrient adequacy of the household diet, and to assess the risk of high micronutrient intakes in the MAPS tool cost and effectiveness module.
