project:
  type: book
  output-dir: docs
book:
  title: "MAPS technical guide cost effectiveness"
  author: "MAPS Team" #Katie Adams 
  date: "11/26/2024" #USA format NB.
 #site-url: https://CEmodels.micronutrient.support/
 
  sidebar: 
    logo: images/MAPS_sticker_purple.png  
    search: true
  
  chapters:
    - index.qmd
    - intro.qmd
    - 01_DefineIntervention.qmd
    - 02_Methods.qmd
  #  - 03_MethodsMetrics HOLD.qmd
    - 03_MethodsMetrics.qmd
    - 04_Interpretation.qmd
   # - summary.qmd
    - references.qmd

bibliography: references.bib

# format:
#   html:
#     theme: cosmo
#   pdf:
#     documentclass: scrreprt
# 
# editor: visual


# Placeholder templates for tool version replacement script
tool-version: <span class="replace">tool-version</span>
api-version: <span class="replace">api-version</span>
data-seed: <span class="replace">data-seed</span>
data-schema: <span class="replace">data-schema</span>
#bibliography: references.bib

format:
  html:
    theme: cosmo

    # Script to fetch live tool and api versions and replace into content
    include-after-body:
      - file: fetchLiveToolVersions.html 
  pdf:
    documentclass: scrreprt

editor: visual


