# References {.unnumbered}

Adams K.P., Vosti S.A., Mbuya M.N.N., Friesen V.M. & Engle-Stone R. (2022). Update on analytical methods and research gaps in the use of household consumption and expenditure survey data to inform the design of food-fortification programs. Advances in Nutrition, 13, 953-969. [https://doi.org/10.1093/advances/nmac021](https://doi.org/10.1093/advances/nmac021){target="_blank"}

Allen L.H., Carriquiry A.L. & Murphy S.P. (2019). Perspective: Proposed harmonized nutrient reference values for populations. Advances in Nutrition, 11, 469-483 [https://doi.org/10.1093/advances/nmz096](https://doi.org/10.1093/advances/nmz096){target="_blank"}

Bailey L.B. (2000). New standard for dietary folate intake in pregnant women123. The American Journal of Clinical Nutrition, 71, 1304S-1307S [https://doi.org/10.1093/ajcn/71.5.1304s](https://doi.org/10.1093/ajcn/71.5.1304s){target="“_blank”"}

Bouis H.E., Hotz C., McClafferty B., Meenakshi J.V. & Pfeiffer W.H. (2011). Biofortification: A new tool to reduce micronutrient malnutrition. Food and Nutrition Bulletin, 32, S31-S40 [https://journals.sagepub.com/doi/10.1177/15648265110321S105](https://journals.sagepub.com/doi/10.1177/15648265110321S105){target="“_blank”"}

Bureau of Economic Analysis (2020). Table 1.1.9. Implicit price deflators for gross domestic product. <https://apps.bea.gov/iTable/iTable.cfm?reqid=19&step=3&isuri=1&1921=survey&1903=13#reqid=19&step=3&isuri=1&1921=survey&1903=13>

Centers for Disease Control and Prevention (2024). Maternal diet and breastfeeding. [https://www.cdc.gov/breastfeeding-special-circumstances/hcp/diet-micronutrients/maternal-diet.html](https://www.cdc.gov/breastfeeding-special-circumstances/hcp/diet-micronutrients/maternal-diet.html){target="“_blank”"}

Coates J., Colaiezzi B., Fiedler J.L., Wirth J., Lividini K. & Rogers B. (2012). A program needs-driven approach to selecting dietary assessment methods for decision-making in food fortification programs. Food and Nutrition Bulletin, 33, S146-S156 [https://journals.sagepub.com/doi/abs/10.1177/15648265120333S202](https://journals.sagepub.com/doi/abs/10.1177/15648265120333S202){target="“_blank”"}

de Valença A.W., Bake A., Brouwer I.D. & Giller K.E. (2017). Agronomic biofortification of crops to fight hidden hunger in sub-saharan Africa. Global Food Security, 12, 8-14 [https://doi.org/10.1016/j.gfs.2016.12.001](https://doi.org/10.1016/j.gfs.2016.12.001){target="“_blank”"}

Fiedler J.L. (2013). Towards overcoming the food consumption information gap: Strengthening household consumption and expenditures surveys for food and nutrition policymaking. Global Food Security, 2, 56-63 [https://doi.org/10.1016/j.gfs.2012.09.002](https://doi.org/10.1016/j.gfs.2012.09.002){target="“_blank”"}

Food and Agricultural Organization of the United Nations & World Health Organization (2001). Human energy requirements. Report of a joint FAO/WHO/UNU expert consultation. Rome,17–24 October 2001 [https://openknowledge.fao.org/server/api/core/bitstreams/62ae7aeb-9536-4e43-b2d0-55120e662824/content](https://openknowledge.fao.org/server/api/core/bitstreams/62ae7aeb-9536-4e43-b2d0-55120e662824/content){target="“_blank”"}

Food and Agriculture Organization of the United Nations & The World Bank (2018). Food data collection in household consumption and expenditure surveys. Guidelines for low-and middle-income countries. FAO and the World Bank, Rome.

Institute of Medicine (2001). Dietary reference intakes for vitamin a, vitamin k, arsenic, boron, chromium, copper, iodine, iron, manganese, molybdenum, nickel, silicon, vanadium, and zinc. National Academies Press, Washington, D.C.

Olson R., Gavin-Smith B., Ferraboschi C. & Kraemer K. (2021). Food fortification: The advantages, disadvantages and lessons from Sight and Life programs. Nutrients, 13 [https://doi.org/10.3390/nu13041118](https://doi.org/10.3390/nu13041118){target="“_blank”"}

Saltzman A., Birol E., Bouis H.E., Boy E., De Moura F.F., Islam Y. & Pfeiffer W.H. (2013). Biofortification: Progress toward a more nourishing future. Global Food Security, 2, 9-17 [https://doi.org/10.1016/j.gfs.2012.12.003](https://doi.org/10.1016/j.gfs.2012.12.003){target="“_blank”"}

Sanders G.D., Neumann P.J., Basu A., Brock D.W., Feeny D., Krahn M., . . . Ganiats T.G. (2016). Recommendations for conduct, methodological practices, and reporting of cost-effectiveness analyses: Second panel on cost-effectiveness in health and medicine. JAMA, 316, 1093-1103 [https://doi.org/10.1001/jama.2016.12195](https://doi.org/10.1001/jama.2016.12195){target="“_blank”"}

Turner H.C., Sandmann F.G., Downey L.E., Orangi S., Teerawattananon Y., Vassall A. & Jit M. (2023). What are economic costs and when should they be used in health economic studies? Cost Effectiveness and Resoure Allocation, 21, 31 [https://doi.org/10.1186/s12962-023-00436-w\\](https://doi.org/10.1186/s12962-023-00436-w){target="“_blank”"}

United Nations, Department of Economic and Social Affairs, Population Division (2019). World population prospects 2019, online edition. Rev. 1.,[https://population.un.org/wpp/](https://population.un.org/wpp/){target="“_blank”"}

USAID Advancing Nutrition (2023a). Methods guide: Needs assessment and design methodology to guide large-scale food fortification and broader programming to improve diets. USAID Advancing Nutrition, Arlington, VA, [https://www.advancingnutrition.org/sites/default/files/2023-10/usaid_an_lsff_methodsguide.pdf](https://www.advancingnutrition.org/sites/default/files/2023-10/usaid_an_lsff_methodsguide.pdf){target="“_blank”"}

USAID Advancing Nutrition (2023b). Operational overview: Needs assessment and design methodology to guide large-scale food fortification and broader programming to improve diets. USAID Advancing Nutrition, Arlington, VA, <https://www.advancingnutrition.org/sites/default/files/2023-10/usaid_an_lsff_operationalguide.pdf>

WHO Programme of Nutrition (1998). Complementary feeding of young children in developing countries: A review of current scientific knowledge. WHO, Geneva, Switzerland.

World Health Organization (2003). Making choices in health: WHO guide to cost-effectiveness analysis. (eds T. Tan-Torres Edejer, B. R., T. Adams, R. Hutubessy, A. Acharya, D.B. Evans, et al.). Geneva, Switzerland.
